---
title: "Dilution gauging"
author: "Tim Covino"
date: "9/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
library(lubridate)
library(tibbletime)
```

```{r}
df <- read_csv('hydrology/3_dilution_gauging/R/data/corrected_conductivity_working.csv')

df_tt <- as_tbl_time(df, index = Time)

#df_tt <- df_tt %>% 
  mutate(time_s= as.numeric(Run_time)) %>% 
  mutate(Time = as.POSIXct(Time,format="%H:%M:%S"))
```

```{r}
ggplotly(df_tt %>%
  ggplot(aes(x = Time, y = Cond_cor)) +
  geom_point())
```

```{r}

dist <- 20 

## injection 1
mass1<-223.8
injTime1 <- "15:11:35"
## injection 2
mass2<-418.4
injTime2 <- "15:21:40"
## injection 3
mass3<-312.6
injTime3 <- "15:41:45"
```

```{r}

inj_1 <- df_tt %>% 
  filter_time(injTime1 ~ '15:24:00') %>% 
  mutate(time_since_inj = Run_time - 2045)

inj_2 <- df_tt %>% 
  filter_time(injTime2 ~ '15:40:00') %>% 
  mutate(time_since_inj = Run_time - 2650)

inj_3 <- df_tt %>% 
  filter_time(injTime3 ~ '15:49:30') %>% 
  mutate(time_since_inj = Run_time - 3855)
```

```{r}
ggplotly(inj_3 %>% 
  ggplot(aes(x = time_since_inj, y = bg_sc)) +
  geom_point())
```

```{r}
inj_3 <- inj_3 %>% 
  mutate(bg_sc = Cond_cor - 0.756) %>% 
  filter(bg_sc > 0)
```

```{r}
peak = 45
median = 65
  
fiveRecovery.idx1<- which.min(abs(inj_3$recovery-.05)) # find the index of the point that has recovery equal to .05 (or 5%)
fiftyRecovery.idx1<- which.min(abs(inj_3$recovery-0.5))
ninetyfiveRecoery.idx1<- which.min(abs(inj_3$recovery-0.95))

five_time <- inj_3[5, 6]
fifty_time <- inj_3[13, 6]
ninety_five_time <- inj_3[35, 6]


five_vel <- dist/five_time
fifty_vel <- dist/fifty_time
ninety_five_vel <- dist/ninety_five_time

```

```{r}
inj_3 <- inj_3 %>% 
  mutate(NaCl = bg_sc/2) %>% # convert from conductivity (mS/cm) to concentration NaCl (g/L)
  mutate(IntC_s1 = NaCl+lag(NaCl,default=0))%>% # first step of integration 
  mutate(IntC = cumsum(IntC_s1*.5*5))%>% # complete integration
  mutate(recovery = IntC/max(IntC)) # Calculate recovery

# Determine flow
Q1<-mass1/max(inj_3$IntC)
```

```{r}
ggplotly(inj_3 %>% 
  ggplot() +
  geom_point(aes(x = time_since_inj, recovery))
)
```











