---
title: "WR417 Tutorial"
author: "Daniel Dominguez"
date: "11/30/2020"
output: 
  html_document:
    toc: true
    toc_depth: 3
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(RColorBrewer)
install.packages("RNRCS")
library(RNRCS)
install.packages("githubinstall")
install.packages("devtools")
library(devtools)
require(devtools)
install.packages("cachem")

devtools::install_github("rhlee12/RNRCS")
library(githubinstall)
gh_install_packages("RNRCS")
githubinstall("RNRCS")

```

#Data download

First we need to download the data for our two sites, site id 2009 is located in Wakulla, FL, and site 2167 is located in Dugway, UT.
```{r}

Florida<- grabNRCS.data(network="SCAN", 
                     site_id = "2009",
                     DayBgn = "2017-01-01",
                     DayEnd = "2019-12-31",
                     timescale = "hourly")


Utah<- grabNRCS.data(network="SCAN", 
                     site_id = "2167",
                     DayBgn = "2017-01-01",
                     DayEnd = "2019-12-31",
                     timescale = "hourly")

```

# Data cleaning

```{r}
#First select and rename columns to easier names to work with and then convert to units we want.
Florida_clean <- Florida%>%
  dplyr::select(Date,
                Avg_temp_f= Air.Temperature.Average..degF.,
                Max_temp_f= Air.Temperature.Maximum..degF.,
                Min_temp_f= Air.Temperature.Minimum..degF.,
                RH_max=Relative.Humidity.Maximum..pct.,
                RH_min= Relative.Humidity.Minimum..pct.,
                Rn_W_m2= Solar.Radiation.Average..watt.m2.,
                u_mph=Wind.Speed.Average..mph.)%>%
  mutate(u_km_d= u_mph*0.44704*24,
         Tmean_C= (Avg_temp_f-32)*(5/9),
         Tmax_C= (Max_temp_f-32)*(5/9),
         Tmin_C= (Avg_temp_f-32)*(5/9),
         Rn_mm_d= Rn_W_m2/1000/2500000*1000*86400)
  
#Extract the date so we can get daily statistics
Florida_clean$date= as.Date(Florida_clean$Date)

Utah_clean <- Utah%>%
  dplyr::select(Date,
                Avg_temp_f= Air.Temperature.Average..degF.,
                Max_temp_f= Air.Temperature.Maximum..degF.,
                Min_temp_f= Air.Temperature.Minimum..degF.,
                RH_max=Relative.Humidity.Maximum..pct.,
                RH_min= Relative.Humidity.Minimum..pct.,
                Rn_W_m2= Solar.Radiation.Average..watt.m2.,
                u_mph=Wind.Speed.Average..mph.)%>%
  mutate(u_km_d= u_mph*0.44704*24,
         Tmean_C= (Avg_temp_f-32)*(5/9),
         Tmax_C= (Max_temp_f-32)*(5/9),
         Tmin_C= (Avg_temp_f-32)*(5/9),
         Rn_mm_d= Rn_W_m2/1000/2500000*1000*86400)
  
Utah_clean$date= as.Date(Utah_clean$Date)

```

# Summarize data for daily statistics

```{r}

FL<- Florida_clean%>%
  dplyr::select(date, 
                u_km_d,
                Tmean_C,
                Tmax_C,
                Tmin_C,
                RH_max,
                RH_min,
                Rn_mm_d)%>%
  group_by(date)%>%
  summarise(across(where(is.numeric),~ mean(.,na.rm= TRUE)))%>%
  mutate(site="FL")

UT<- Utah_clean%>%
  dplyr::select(date, 
                u_km_d,
                Tmean_C,
                Tmax_C,
                Tmin_C,
                RH_max,
                RH_min,
                Rn_mm_d)%>%
  group_by(date)%>%
  summarise(across(where(is.numeric),~ mean(.,na.rm= TRUE)))%>%
  mutate(site="UT")

```
# Penman
## Florida
```{r}
FL$e_min= 0.6108*exp((17.27*FL$Tmin_C)/(FL$Tmin_C+237.3))
FL$e_max= 0.6108*exp((17.27*FL$Tmax_C)/(FL$Tmax_C+237.3))
FL$e= (FL$e_max+FL$e_min)/2
FL$ea_kPa= ((FL$RH_max+FL$RH_min)/2)/100*FL$e
FL$VPD= FL$e-FL$ea_kPa

FL$sspd= (2503^((17.7*FL$Tmean_C)/(FL$Tmean_C+237.3)))/((FL$Tmean_C+237.3)^2)
FL$u_m_s= FL$u_km_d/86.4
psycon= 0.055
lambda= 2.5

FL$PE1= ((FL$sspd/(FL$sspd+psycon))*FL$Rn_mm_d)
FL$PE2=(psycon*(6.43*(1+(0.536*FL$u_m_s)))*FL$VPD)/(lambda*(FL$sspd+psycon))
FL$PE= FL$PE1+FL$PE2

#sum of yearly PE
FL$year= year(FL$date)

FL_sum<- FL%>%
  group_by(year)%>%
  summarize(total_e= sum(PE))%>%
  mutate(site= "Florida",
         method="Penman")
```

## Utah
```{r}
UT$e_min= 0.6108*exp((17.27*UT$Tmin_C)/(UT$Tmin_C+237.3))
UT$e_max= 0.6108*exp((17.27*UT$Tmax_C)/(UT$Tmax_C+237.3))
UT$e= (UT$e_max+UT$e_min)/2
UT$ea_kPa= ((UT$RH_max+UT$RH_min)/2)/100*UT$e
UT$VPD= UT$e-UT$ea_kPa

UT$sspd= (2503^((17.7*UT$Tmean_C)/(UT$Tmean_C+237.3)))/((UT$Tmean_C+237.3)^2)
UT$u_m_s= UT$u_km_d/86.4


UT$PE1= ((UT$sspd/(UT$sspd+psycon))*UT$Rn_mm_d)
UT$PE2=(psycon*(6.43*(1+(0.536*UT$u_m_s)))*UT$VPD)/(lambda*(UT$sspd+psycon))
UT$PE= UT$PE1+UT$PE2

#sum of yearly PE
UT$year= year(UT$date)

UT_sum<- UT%>%
  group_by(year)%>%
  summarize(total_e= sum(PE))%>%
  mutate(site= "Utah",
         method="Penman")
```

# Figures
## Florida
```{r}
ggplot(FL, aes(x=date))+
  geom_line(aes(y=PE), size= 0.3, color="blue")+
  theme_classic()+
  labs(x= "Date",
       y="Potential Evaporation (mm/d)")+
  scale_x_date(breaks = "3 month",
               date_labels = "%b-%y")+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))+
  scale_color_manual(name= "Measurement",
                     labels="Potential Evaporation",
                     values= "darkred")

```

## Utah
```{r}
ggplot(UT, aes(x=date))+
  geom_line(aes(y=PE), size= 0.3,  color="darkred")+
  theme_classic()+
  labs(x= "Date",
       y="Potential Evaporation (mm/d)")+
  scale_x_date(breaks = "3 month",
               date_labels = "%b-%y")+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

###Stacking
```{r}
Penman<- rbind(UT,FL)
```


# Blaney
## Latitude values and Resummarize data   
```{r}
lat_30<- tibble(month= c(1:12),
                value= c(.24,.25,.27,.29,.31,.32,.31,.30,.28,.26,.24,.23))
#Because Blaney uses monthly statistics first we have to resummarize data but first we are going to extract year and month

FL$year= year(FL$date)
FL$month= month(FL$date)

FL_month<- left_join(FL, lat_30, by="month")%>%
  dplyr::select(year,month, Tmin_C,
                Tmax_C, value)%>%
  group_by(year,month)%>%
    summarise(across(where(is.numeric),~ mean(.,na.rm= TRUE)))%>%
      mutate(Date = ymd(paste(year,month,01,sep='-')))%>%
  mutate(ET= value*((0.46*(Tmax_C+Tmin_C)/2))+8,
         site="FL")

FL_year_sum<- FL_month%>%
  group_by(year)%>%
  summarize(total_e= sum(ET)*12)%>%
  mutate(site= "Florida",
         method= "Blaney")
```

