---
title: "q_c_fig_2"
author: "tim covino"
date: "11/2/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, echo = FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
library(lubridate)
library(here)
library(ggthemes)
library(scales)
library(cowplot)
library(plotly)
library(na.tools)
library(tseries)

```


```{r}

df <- read_csv(here('data/q_c_11_2_20.csv'))

q <- read_csv(here('data/csasn_q_2011.csv'))

p <- read_csv(here('data/precip.csv'))

```


```{r}

head(q)

df <- df %>%
  mutate(Date = mdy(Date)) %>% 
  mutate(year = year(Date))

q <- q %>%
  mutate(Date = mdy(Date))

p <- p %>%
  mutate(Date = mdy(Date))

df_elev <- df %>%
  filter(year == 2011) 

df_elev <- df_elev %>%
  mutate(DIN = NO3+ NH4)

i8_in <- df_elev %>% 
  filter(Site == 'I8-In')

din_max <- max(df_elev$DIN, na.rm = TRUE)
din_min <- min(df_elev$DIN, na.rm = TRUE)
din_mean <- mean(df_elev$DIN, na.rm = TRUE)

i8_in_all <- df %>% 
  filter(Site == 'I8-In')

i8_in_q <- q %>% 
  filter(Site == 'I8-In')

i8_out <- df_elev %>% 
  filter(Site == 'I8-Out')

i8_out_all <- df %>% 
  filter(Site == 'I8-Out')

i8_out_q <- q %>% 
  filter(Site == 'I8-Out')

p_in <- df_elev %>% 
  filter(Site == 'P-In')

p_in_all <- df %>% 
  filter(Site == 'P-In')

p_q <- q %>% 
  filter(Site == 'P-In')

  

```


```{r}
i8in_din_max <- max(i8_in$DIN)
i8in_din_mean <- mean(i8_in$DIN)
i8in_din_min <- min(i8_in$DIN)

i8out_din_max <- max(i8_out$DIN, na.rm = TRUE)
i8out_din_mean <- mean(i8_out$DIN, na.rm = TRUE)
i8out_din_min <- min(i8_out$DIN, na.rm = TRUE)

pin_din_max <- max(p_in$DIN, na.rm = TRUE)
pin_din_mean <- mean(p_in$DIN, na.rm = TRUE)
pin_din_min <- min(p_in$DIN, na.rm = TRUE)

```




```{r}
f <- ggplot(df_elev, aes(x = Date, y = NH4, color = 'green')) + 
  geom_point() + 
  geom_line() +
  theme_few()

g <- ggplotly(f)

g       
max(df$PO4)
```


```{r}
ggplot(i8_out, aes(x = Q, y = NO3)) + 
  geom_point() + 
  stat_smooth(method = lm) +
  theme_few()

i8_out_q_no3 <- lm(i8_out$NO3, i8_out$Q)

#Get summary stats for lm
i8out_q_no3.lm = lm(NO3 ~ Q, data = i8_out)
summary(i8out_q_no3.lm)

```


```{r}


p1 <- ggplot () +
  geom_point(data = i8_in, aes(x = Date, y = NO3*2.7), color = 'darkgreen', shape = 16, size = 2) +
  geom_line(data = i8_in, aes(x = Date, y = NO3*2.7), color = 'darkgreen', linetype = 'dashed') +
  geom_point(data = i8_in, aes(x = Date, y = PO4*2.7), color = 'deeppink', shape = 15, size = 2) +
  geom_line(data = i8_in, aes(x = Date, y = PO4*2.7), color = 'deeppink', linetype = 'dashed') +
  geom_point(data = i8_in, aes(x = Date, y = NH4*2.7), color = 'dodgerblue', shape = 17, size = 2) +
  geom_line(data = i8_in, aes(x = Date, y = NH4*2.7), color = 'dodgerblue', linetype = 'dashed') +
  geom_line(data = i8_q, aes(x = Date, y = Q_L_s), color = 'blue') +
  labs(y = "", x = "") +
  theme(legend.position = 'bottom') +
  theme(panel.grid.major.x = element_line( size = 0.3, color= 'black', linetype = 'dashed')) +
  theme_few()


png(filename = 'ms/response_to_review/figs/f2_i8in.png',width=6, height=3,
    units='in',res=300)

p1 + scale_y_continuous(sec.axis = sec_axis(~ . / 2.7)) +
  theme_few(base_size = 20) +
  theme(panel.grid.major.x = element_line( size = 0.3, color= 'black', linetype = 'dashed')) +
  scale_x_date(date_labels = "%m/%d/%y")

dev.off()

```


```{r}

p2 <- ggplot () +
  geom_point(data = i8_out, aes(x = Date, y = NO3*6.2), color = 'darkgreen', shape = 16, size = 2) +
  geom_line(data = i8_out, aes(x = Date, y = NO3*6.2), color = 'darkgreen', linetype = 'dashed') +
  geom_point(data = i8_out, aes(x = Date, y = PO4*6.2), color = 'deeppink', shape = 15, size = 2) +
  geom_line(data = i8_out, aes(x = Date, y = PO4*6.2), color = 'deeppink', linetype = 'dashed') +
  geom_point(data = i8_out, aes(x = Date, y = NH4*6.2), color = 'dodgerblue', shape = 17, size = 2) +
  geom_line(data = i8_out, aes(x = Date, y = NH4*6.2), color = 'dodgerblue', linetype = 'dashed') +
  geom_line(data = i8_out_q, aes(x = Date, y = Q_L_s), color = 'blue') +
  labs(y = "", x = "") +
  theme(legend.position = 'bottom') +
  theme(panel.grid.major.x = element_line( size = 0.3, color= 'black', linetype = 'dashed')) +
  theme_few()

png(filename = 'ms/response_to_review/figs/f2_i80out.png',width=6, height=3,
    units='in',res=300)

p2 + scale_y_continuous(sec.axis = sec_axis(~ . / 6.2)) +
  theme_few(base_size = 20) +
  theme(panel.grid.major.x = element_line( size = 0.3, color= 'black', linetype = 'dashed')) +
  scale_x_date(date_labels = "%m/%d/%y")

dev.off()

```


```{r}

p3 <- ggplot () +
  geom_point(data = p_in, aes(x = Date, y = NO3*6.4), color = 'darkgreen', shape = 16, size = 2) +
  geom_line(data = p_in, aes(x = Date, y = NO3*6.4), color = 'darkgreen', linetype = 'dashed') +
  geom_point(data = p_in, aes(x = Date, y = PO4*6.4), color = 'deeppink', shape = 15, size = 2) +
  geom_line(data = p_in, aes(x = Date, y = PO4*6.4), color = 'deeppink', linetype = 'dashed') +
  geom_point(data = p_in, aes(x = Date, y = NH4*6.4), color = 'dodgerblue', shape = 17, size = 2) +
  geom_line(data = p_in, aes(x = Date, y = NH4*6.4), color = 'dodgerblue', linetype = 'dashed') +
  geom_line(data = p_q, aes(x = Date, y = Q_L_s), color = 'blue') +
  labs(y = "", x = "") +
  theme(legend.position = 'bottom') +
  theme(panel.grid.major.x = element_line( size = 0.3, color= 'black', linetype = 'dashed')) +
  theme_few()

png(filename = 'ms/response_to_review/figs/f2_pin.png',width=6, height=3,
    units='in',res=300)

p3 + scale_y_continuous(sec.axis = sec_axis(~ . / 6.4)) +
  theme_few(base_size = 20) +
  theme(panel.grid.major.x = element_line( size = 0.3, color= 'black', linetype = 'dashed')) +
  scale_x_date(date_labels = "%m/%d/%y")

dev.off()

str(p_in)
```


```{r}

min <- as.Date('2011-06-04')
max <- as.Date('2011-10-03')

png(filename = 'ms/response_to_review/figs/rain_f2.png', width=6, height=2,
    units='in',res=300)

ggplot(p, aes(x = Date, y = P_mm)) +
  geom_col(size = 2, color = 'blue') +
  theme_few(base_size = 14) +
  ylab(expression(Rain~(mm~d^-1))) +
  scale_y_reverse() +
  xlab('') +
  scale_x_date(limits = c(min, max))

dev.off()
```


```{r}

ggplot(p, aes(x = Date, y = P_mm)) +
  geom_col(size = 4)

ggplot(df, aes(x = Date, y = NO3, color = Site)) +
  geom_point()

df2 <- df %>% 
  mutate(ymd())
  filter()

summary(df_elev$NO3, na.rm = TRUE)

max(df$NH4, na.rm = TRUE)

```

