---
title: "ESS H"
author: "Tim Covino"
date: "4/27/2022"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, results = TRUE)

```

```{r}
library(tidyverse)
library(here)
library(plotly)
```

```{r}
df <- read_csv(here('ESS_faculty/data/ESS_H.csv'))
```

```{r}
 ggplotly(df %>% 
 
    ggplot(aes(x = Years, y = H, color = Name)) +
  geom_point() +
    theme_linedraw() +
    labs(x = "Years since PhD", y = "H index")
  )
```


```{r}
bar_df <- read_csv(here('ESS_faculty/data/H_bar.csv'))

ggplotly(bar_df %>% 
  ggplot() +
  geom_col(aes(x = Name, y = H, fill = Years)) +
  theme_linedraw() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(y = 'H index', x = ''))
  
ggplotly(bar_df %>% 
            ggplot(aes(x = Years, y = H, color = Name)) +
            geom_point() +
           labs(y = 'H index', x = 'Years since PhD') +
           theme_linedraw() +
           theme(legend.title = element_blank())
         )
```


```{r}
bar_df_unique <- read_csv(here('ESS_faculty/data/H_bar_unique_year.csv'))
ggplotly(bar_df_unique %>% 
            ggplot() +
            geom_col(aes(x = Years, y = H, fill = Name)) +
           labs(x = 'Years since PhD', y = 'H index') +
           theme_linedraw() +
           theme(legend.title = element_blank())
         )
```

```{r}
bar_df <- bar_df %>% 
  mutate(H_to_year = H/Years) 

order_df <- bar_df %>% 
  arrange(H_to_year)

order_df %>% 
  ggplot(aes(x = reorder(Name, H_to_year), y = H_to_year)) +
  geom_col() +
  labs(y = 'H-index/Years from PhD (-)', x ='') +
  theme_linedraw() +
  theme(axis.text.x = element_text(angle = 90)) 

```











